### ISSUE TITLE
Зачем переделывать update на параметры?

### ISSUE THREAD

**Issue by xor2016** [sergejey/majordomo#1031]
https://github.com/sergejey/majordomo/blob/5271bad4d73fb20afd1097b325b5e46a22350564/lib/mysqli.class.php#L268

Что передача только изменившихся полей, что всей записи обрабатывается mysql одинаково, причем
If you set a column to the value it currently has, MySQL notices this and does not update it. [https://dev.mysql.com/doc/refman/8.0/en/update.html](https://dev.mysql.com/doc/refman/8.0/en/update.html)
В чём выигрыш?
того же самого можно добиться, передавая только нужные поля+id
        $jobs['ID'] = $jobs[$i]['ID'];
        $jobs['PROCESSED'] = 1;
        $jobs['STARTED'] = date('Y-m-d H:i:s');
        SQLUpdate('jobs', $jobs);
и, по-прежнему, можно свой индекс выбрать, а не зашитый хардкодом теперь ID

**Comment by Alexandr-logrus** [comment]
ты принципмально против данной правки или в текущей реализации?

**Comment by xor2016** [comment]
эм, у базовой функции есть список параметров, именованных. использование одного из них не по назначению, да и с потерей универсальности - не является оптимизацией, которой можно добиться, кстати, штатно и без включения в код функции доп. обработчика. да я и не вижу особой оптимизации при выводе в апдейт части полей вместо всего массива. апдейт по-любому возвращает только количество измененных полей+см. доку. тут функции откомпилированного мускула подменяем работой интерпретатора(

**Comment by Alexandr-logrus** [comment]
т.е. вывод в апдейт части полей, без особенно титле, лог, коде которые не меняются и большие, с дальнейшей конкатенацией не является оптимизацией?
уменьшение трафика в сторону мскл не является оптимизацией?

**Comment by xor2016** [comment]
перечитай мой первый коммент со слов "того же самого можно добиться, передавая только нужные поля+id"

**Comment by sergejey** [comment]
прихожу к мысли, что действительно имеет смысл просто изначальный запрос упростить и не вводить новые сущности в библиотеку

**Comment by xor2016** [comment]
реализовано
