### ISSUE TITLE
Вывод статуса батареи для нескольких ПУ

### ISSUE THREAD

**Issue by kirush0280** [sergejey/majordomo#1044]
Датчик Движения
Датчик протечки
Термостат

**Comment by sergejey** [comment]
Про датчики Движения и Протечки не понял запрос -- в шаблонах оно же и так добавлено.
Насчёт термостата -- понял.

**Comment by kirush0280** [comment]
Спасибо, посмотрел внимательно...да есть, почему то у меня не обновились файлы - обновил руками.
