### ISSUE TITLE
Uninstall дополнений

### ISSUE THREAD

**Issue by cyneprepou** [sergejey/majordomo#105]
Функция removeMissingSubscribers() не убирает хвосты.

Проверил: концы убирает. Проблема в другом месте.

**Comment by cyneprepou** [comment]
Проблема с модулем festival_tts.
У него отсутствует метод uninstall, по этой причине после удаления модуля в таблице setting концы от модуля остаются.

**Comment by cyneprepou** [comment]
По идее, надо просто добавить метод:

 function uninstall() 
{
  unsubscribeFromEvent($this->name, 'SAY');
  parent::uninstall();
 }

С inova_tts все в норме

**Comment by cyneprepou** [comment]
Модуль  	RHVoice TTS - та же ситуация. Нет метода uninstall и хвосты остаются.

**Comment by cyneprepou** [comment]
Модуль yandex_TTS - та же ситуация. Нет метода uninstall и хвосты остаются.

**Comment by Gelezako** [comment]
у rhvoice есть эта функция
в yandex_TTS и festival_tts добавил и отправил пул реквест на добавление
