### ISSUE TITLE
Сертификат fullchain.pem не проходит проверку

### ISSUE THREAD

**Issue by Vladimir1832** [sergejey/majordomo#1079]
Сертификат fullchain.pem не проходит проверку. Соединение MQTT по порту 8883 не устанавливается (error:0A000086:SSL routines::certificate verify failed). Лечится только установкой 'verify_peer' => false, в файле phpMQTT.php. Наверное надо опубликовать другой сертификат.

**Comment by sergejey** [comment]
Можно попробовать новый сертификат (из альфы)?

**Comment by Vladimir1832** [comment]
Ок. Спасибо

**Comment by Vladimir1832** [comment]
Ок. Спасибо
