### ISSUE TITLE
при нескольких значениях свойства в течение секунды неверно может отображаться история

### ISSUE THREAD

**Issue by xor2016** [sergejey/majordomo#1093]
https://github.com/sergejey/majordomo/blob/076c4ebf843b9ec9d0b9b2358ba942d95c504232/pChart/index.php#L158

предлагается при равенстве времён дополнительная сортировка по ид:

`
return ($a['ID'] < $b['ID']) ? -1: 1;
`
и, наверное, правильно ещё и сюда добавить сортировку по ид для корректного отбора 20 записей:

` $history = SQLSelect("SELECT ID, VALUE, ADDED, SOURCE FROM $history_table WHERE VALUE_ID='" . $pvalue['ID'] . "' ORDER BY ADDED DESC, ID desc LIMIT 20");`

**Comment by Alexandr-logrus** [comment]
а не смотрел (не помню) оно из очереди истории то по тому же порядку (как и попало в очередь) в пхистори запишет?

**Comment by xor2016** [comment]
Очередь не смотрел(
Да, в pchart влияние в OPTIMIZE_LOG будет ещё (там запись есть)
Стоит и туда добавить ID desc
`            if ($_GET['subop'] == 'optimize') {
                $data = SQLSelect("SELECT * FROM $history_table WHERE VALUE_ID='" . $pvalue['ID'] . "' ORDER BY ADDED DESC, ID desc");`

а так, вроде, только читает. Я налетел на просмотре истории свойства. Оптимизацией в этом окне не пользуюсь

**Comment by sergejey** [comment]
Исправлено в альфе.
