### ISSUE TITLE
порядок в истории

### ISSUE THREAD

**Issue by xor2016** [sergejey/majordomo#1096]
https://github.com/sergejey/majordomo/blob/ee204e8207893565f44a214646f09ed379208b40/pChart/index.php#L158

а вот тут не надо вместо return 0 при сортировке уже в php при равенстве времени вернуть сортировку по id?
`return ($a['ID'] < $b['ID']) ? -1: 1;`

**Comment by sergejey** [comment]
В альфе уже так и есть https://github.com/sergejey/majordomo/blob/bbbec97e99ed7f199a41326bda5dd8e72c3627f3/pChart/index.php#L158
