### ISSUE TITLE
предлагаю замену циклов php на простые запросы

### ISSUE THREAD

**Issue by xor2016** [sergejey/majordomo#1097]
https://github.com/sergejey/majordomo/blob/bbbec97e99ed7f199a41326bda5dd8e72c3627f3/scripts/startup_maintenance.php#L182
вот эти секции кода 
// removing incorrect pvalues
// fixing property names
предлагается заменить на 4 запроса:

```
//чистим табл. значений от несуществующих объектов
SQLExec("DELETE FROM pvalues where NOT EXISTS (SELECT ID FROM objects WHERE objects.ID=pvalues.OBJECT_ID);");
//чистим табл. значений от несуществующих свойств
SQLExec("DELETE FROM pvalues where NOT EXISTS (SELECT ID FROM properties WHERE properties.ID=pvalues.PROPERTY_ID);");
//чистим табл. истории от несуществующих значений
SQLExec("DELETE FROM phistory where NOT EXISTS (SELECT ID FROM pvalues WHERE pvalues.ID=phistory.VALUE_ID);");
//исправляем поле PROPERTY_NAME
SQLExec("UPDATE pvalues
         JOIN objects ON pvalues.OBJECT_ID = objects.id
         JOIN properties ON pvalues.PROPERTY_ID = properties.id
         SET pvalues.PROPERTY_NAME=CONCAT_WS('.', objects.TITLE, properties.TITLE)
         WHERE pvalues.PROPERTY_NAME != CONCAT_WS('.', objects.TITLE, properties.TITLE);");
```

**Comment by sergejey** [comment]
А какое улучшение даёт эта замена? Я бы понял если б в текущем коде добавить запись в лог (вместо echo) для того, чтобы операции по автоматическому исправлению не уходили "в никуда", но выше предлагается сделать запрос, который вообще не будет следов оставлять.

**Comment by xor2016** [comment]
Вообще, это исправление того, "чего не должно быть никогда". Обычно реляционные базы такое исправляют сами. Если дело в том, что надо построчно смотреть для анализа эти ошибки, то предложение снимается.

Встречный вопрос - Сейчас этот файл запускается только при старте системы?
Если да, то это не очень хорошо, если идёт правка структуры и при этом возможны такие ошибки, то либо периодически исправлялку неплохо запускать или по требованию.

**Comment by sergejey** [comment]
В базовом образе этот файл подключается из скрипта, который стартует каждую ночь, но возможно это имеет смысл переделать, т.к. не у всех может быть прописан этот скрипт -- в таком случае действительно его выполнение происходит только на запуске. Но это отдельная история не в рамках данного предложения.

**Comment by xor2016** [comment]
согласен, при регулярном запуске минимизированы последствия и предложение не добавляет фич)
Закрываем задачу
