### ISSUE TITLE
Убрать в скриптах автолинк по умолчанию Да

### ISSUE THREAD

**Issue by xor2016** [sergejey/majordomo#1098]
https://github.com/sergejey/majordomo/blob/bbbec97e99ed7f199a41326bda5dd8e72c3627f3/modules/scripts/scripts_edit.inc.php#L121
Пишется скрипт без всяких задних мыслей, короткий - переключение двух лампочек. Запускаю его по кнопке интерфейса. Он работает. Добавил в первую строку условие на проверку свойства (устройство онлайн), нажал ctrl+S.
А модуль сам прилинковал это свойство к модулю и лампочки начали переключаться при изменении свойства(
Еле нашёл(
Как я понял, если такая ситуация возникнет с функциями времени в первой строке, это будет и по часам само работать.
Крыжик автолинка сам появляется внизу окна кода и по умолчанию установлена опция привязки объекта.свойства.
Предлагается ставить там Нет, чтобы изменения, если уж они кому-то нужны, принимались пользователем

**Comment by xor2016** [comment]
ps. не видел в коде, что при установке Нет чистится связь свойства с модулем

**Comment by xor2016** [comment]
pps. кстати, при чистке потеряшек в startup_maintenance при удалении свойства, вроде, не проверяется наличие привязки его к какому-нибудь модулю и оно теоретически может продолжать существовать в таблице модуля в виде ссылок линкед_объект, линкед_проперти(

**Comment by sergejey** [comment]
Исправлено в альфе - теперь автоматическая линковка не включается по-умочанию.
