### ISSUE TITLE
удаление после рестарта цикла задач, которые должны запуститься в ближайшие 15 минут - для чего?

### ISSUE THREAD

**Issue by xor2016** [sergejey/majordomo#1115]
https://github.com/sergejey/majordomo/blob/ed1bf3d9aad2d8d774c61317c0c0ebfa0e1b7fa3/scripts/cycle_scheduler.php#L26

у меня
1. есть задача, выполняющаяся в момент заката. Если я перезапущу этот цикл или просто перезагружу мдм за 10 минут до этого момента, задача, выходит, удалится?
2. есть задача, перезапускающая себя сама с интервалом, допустим, в 20 минут, если цикл перезапустится и новый старт этой задачи попадёт в  наш 15-минутный  интервал, задача удалится же?

**Comment by sergejey** [comment]
Да, в описанных случаях при перезагрузке задачи не будут выполнены и удалятся. Удаление добавлено из-за частых случаев, когда пользователь некорректно реализует запланированные задачи, что приводит к цикличной перезагрузке сервера без возможности что-то исправить. Сама по себе полная перезагрузка исключительная ситуация и я бы не особо рассчитывал на надёжность таймеров, которые попадают на время загрузки - сейчас это окно принудительно расширено до 15 минут.

**Comment by Alexandr-logrus** [comment]
цикличная перезагрузка может возникать и без использования таймеров если команду отправляли через тлг
а вот скрипты перезагрузки давно мягко скажем некорректы, еще и юзеры там чудят всякое ;(

**Comment by xor2016** [comment]
> Да, в описанных случаях при перезагрузке задачи не будут выполнены и удалятся. Удаление добавлено из-за частых случаев, когда пользователь некорректно реализует запланированные задачи, что приводит к цикличной перезагрузке сервера без возможности что-то исправить. Сама по себе полная перезагрузка исключительная ситуация и я бы не особо рассчитывал на надёжность таймеров, которые попадают на время загрузки - сейчас это окно принудительно расширено до 15 минут.

 так может не ориентироваться на пользователей, которые неккорректно что-то делают, наказывая остальных, "правильных"? может, стоит какой-то параметр добавить, типа, "repair" при рестарте? сейчас же в циклах есть runonce?

**Comment by xor2016** [comment]
Как в винде можно сделать при загрузке:
1. обычный старт 
2. восстановление из бэкапа
3. безопасный старт с удалением задач
чарез 10 секунд выполнится обычный старт

**Comment by sergejey** [comment]
а в чем наказание? я систему рестартую раз в несколько месяцев, не чаще. таймеров тоже хватает, но они не такие "нежные", чтоб для них 15-ти минутная не доступность к трагедии привела. я думал сразу вообще все таймеры на старте чистить, но потом решил, что можно только ближайшие.

**Comment by Alexandr-logrus** [comment]
setTimeOut($ot . "_activity_timeout", "cm('" . $ot . ".onIdle');", $timeout);
есть в таймерах и критичный функционал, в присутствии, охране без них никак, увы и если ранее работало, то с текущим можно и налететь (

правильней в скриптах поправить проблему, хотя и сложнее массово у всех

**Comment by xor2016** [comment]
в системе умного дома заявлен механизм таймеров и запланированных по конкретному времени задач, но теперь при перезагрузке/рестарте цикла шедулера часть из них будет, не глядя, удаляться. ок

"не перегружаться перед рассветом", "не перегружаться перед полночью, если есть шедулед джоб на день", ...

**Comment by sergejey** [comment]
Откатил изменение.
