### ISSUE TITLE
Create STempHumSensors.html  alpha

### ISSUE THREAD

**Issue by andy040670** [sergejey/majordomo#1116]
Ошибка при распаковке архива.

**Comment by sergejey** [comment]
> Ошибка при распаковке архива.

м... может какие-то детали есть?

**Comment by andy040670** [comment]
Из деталей: Unpack failed на трёх линукс системах (Ubuntu 18.04, Debian 11, ADM 3.5.9.RWM1), такое ощущение, что хеш не верный, так как ошибка выскакивает сразу после загрузки архива.

**Comment by sergejey** [comment]
ок, спасибо, похоже сломал установку обновления. буду разбираться.

**Comment by sergejey** [comment]
Исправил в обновлении, но боюсь его придётся накатить вручную, т.к. автоматически не установится. Достаточно скопировать то что распакуется в /var/www/cms/saverestore/temp/majordomo-alpha
