### ISSUE TITLE
Ошибка при выполнении cycle.php

### ISSUE THREAD

**Issue by VinAdmin** [sergejey/majordomo#1117]
`Installing festival_tts ...
2024-03-21 18:00:05  exceptions: commandline: /var/www/majordom.loc/cycle.php
PHP exception: Call to undefined function subscribeFromEvent() in /var/www/majordom.loc/modules/festival_tts/festival_tts.class.php on line 176
Backtrace: #0 /var/www/majordom.loc/lib/module.class.php(335): festival_tts->install()
#1 /var/www/majordom.loc/modules/festival_tts/festival_tts.class.php(23): module->checkInstalled()
#2 /var/www/majordom.loc/modules/control_modules/control_modules.class.php(275) : eval()'d code(1): festival_tts->festival_tts()
#3 /var/www/majordom.loc/modules/control_modules/control_modules.class.php(275): eval()
#4 /var/www/majordom.loc/lib/module.class.php(335): control_modules->install()
#5 /var/www/majordom.loc/modules/control_modules/control_modules.class.php(22): module->checkInstalled()
#6 /var/www/majordom.loc/cycle.php(226): control_modules->__construct()
#7 {main}`

**Comment by Alexandr-logrus** [comment]
поправь в 176 и далее на правильное имя функции
https://github.com/sergejey/majordomo/blob/01b47e2b406f5c3cc47c55a3f3f4a5fc1bd3c542/lib/hooks.inc.php#L10

хз почему это десятилетиями висит, и фестиваль разве вообще рабочий?

**Comment by VinAdmin** [comment]
Фестиваль удалил из modules. Не разбирался какую роль он исполняет.
