### ISSUE TITLE
ПУ датчик освещенности не работает.

### ISSUE THREAD

**Issue by elmax983** [sergejey/majordomo#1121]
При сохранении параметров датчика, получается ошибка. 
В файле **devices_structure.inc.php**
Зачем то, возможно случайно, после строки определения едениц измерения,
 'unit' => array('DESCRIPTION' => LANG_DEVICES_UNIT, '_CONFIG_TYPE' => 'text'),
Все почистили, Верните пожалуйста, чтобы датчик продолжил работать.
```
    // Определение типа устройства "sensor_light" (датчик свещенности)
    'sensor_light' => array(
        'TITLE' => LANG_DEVICES_LIGHT_SENSOR,
        'PARENT_CLASS' => 'SSensors',
        'CLASS' => 'SLightSensors',
        // Свойства датчика освещености
        'PROPERTIES' => array(
            // Единица измерения
            'unit' => array('DESCRIPTION' => LANG_DEVICES_UNIT, '_CONFIG_TYPE' => 'text'), //*  После этой строки у датчика ничего нет, а было!
            
            // Минимальное значение за период
            'periodMinValue' => array('DESCRIPTION' => 'Minimum value for period', 'ONCHANGE' => 'periodMinValueUpdated', 'KEEP_HISTORY' => 365),
            // Время периода для расчета минимального значения (секунды)
            'periodTime' => array('DESCRIPTION' => 'Period to calculate minimum value (seconds)', '_CONFIG_TYPE' => 'num', '_CONFIG_HELP' => 'SdSensorPeriodTime'),
        ),
        // Методы датчика освещенности
        'METHODS' => array(
            // Обновление значения
            'valueUpdated' => array('DESCRIPTION' => 'Value Updated', 'CALL_PARENT' => 1),
            // Обновление минимального значения за период
            'periodMinValueUpdated' => array('DESCRIPTION' => 'Period Min value updated'),
        ),
    ),

**Comment by whitevast** [comment]
А там ничего и не должно быть. Все свойства берутся из родительского класса.
Сейчас создал у себя датчик, никаких ошибок не появилось. Что за ошибка выходит?

**Comment by elmax983** [comment]
Вы знаете, теперь я не смог повторить ошибку, )))  походу пока искал решение пофиксил свои ошибки, (так совпало) и добавил убранную из кода часть:
`            'periodMinValue' => array('DESCRIPTION' => 'Minimum value for period', 'ONCHANGE' => 'periodMinValueUpdated', 'KEEP_HISTORY' => 365),
            'periodTime' => array('DESCRIPTION' => 'Period to calculate minimum value (seconds)', '_CONFIG_TYPE' => 'num', '_CONFIG_HELP' => 'SdSensorPeriodTime'),
        ),
        'METHODS' => array(
            'valueUpdated' => array('DESCRIPTION' => 'Value Updated', 'CALL_PARENT' => 1),
            'periodMinValueUpdated' => array('DESCRIPTION' => 'Period Min value updated'),`
       
После этого все заработало, и решил об этом отписаться. 
Так что простите за панику, и issue можно закрывать.

**Comment by elmax983** [comment]
Ложная тревога
