### ISSUE TITLE
Просьба добавить возможность отключения истории

### ISSUE THREAD

**Issue by alexdan-77** [sergejey/majordomo#1127]
Здравствуйте!

В свойстве **status** класса **SDevices** хотелось бы совсем отключить историю, но при выставлении 0 после перезапуска MD все возвращается принудительно в 365 (дней). Пока приходится выставлять 1, чтобы не сбрасывалось.

**Comment by sergejey** [comment]
В альфе теперь не сбрасывается настройка истории даже при обновлении.
