### ISSUE TITLE
Authentication issue fix

### ISSUE THREAD

**Issue by andy040670** [sergejey/majordomo#1129]
Не работает. Ошибка авторизации.

**Comment by sergejey** [comment]
можно картинку с ошибкой или больше деталей?

**Comment by andy040670** [comment]
Я откатил на предыдущий срез.
Просто не принимает логин / пасс (неверный логин или пароль), всё это происходит на трёх линукс машинах после удаления кук в браузере.

**Comment by sergejey** [comment]
не принимает пароль, который был задан в панелей управления в разделе пользователи? можно всё же подробно объяснить и желательно с картинками...

**Comment by andy040670** [comment]
Да, который задан  в панели управления в разделе пользователи.
Картинки делать нет смысла, так как она такая-хе как и у Вас, за исключением надписи красным цветом "неверный логин или пароль". До этого фикса авторизация работала нормально, да и сейчас работает после подмены application.class.php из предыдущего среза коммитов.

**Comment by sergejey** [comment]
Напишите пожалуйста мне в директ в телеграм (@SergeJey) -- не могу сам найти проблему и, видимо, понадобится Ваша помощь.

**Comment by andy040670** [comment]
Пару дней не будет доступа к системе, да и к компьютеру в общем.

**Comment by andy040670** [comment]
Неа, каая-то чертовщина происходит.
Обновил систему, удалил куки, перезагрузил страницу, ввожу нэйме/пасс, иии...:
![5](https://github.com/sergejey/majordomo/assets/28322160/875c5c08-208f-4f2b-b1c3-a20600496835)
Но-о, удаляю все хвосты в строке адреса, после доменного имени (домкен**/admin?*****) **и захожу в систему как 
уже авторизованный пользователь**
Проверил на одной системе (торчит в сети) со смарфона,  с него доступа по  SOCKS SFTP нет, так что возможности ограничены.

**Comment by sergejey** [comment]
Добры день. Скажите пожалуйста актуальна ли ещё проблема или после обновления системы ушло?

**Comment by andy040670** [comment]
Да, сейчас всё работает. Спасибо.
