### ISSUE TITLE
Предложение по freeboard тоже нужно пул реквестом оформлять?

### ISSUE THREAD

**Issue by xor2016** [sergejey/majordomo#113]
По поводу исправления пойнтера [http://majordomo.smartliving.ru/forum/viewtopic.php?f=7&t=3607&p=50837#p50397](url)
уже есть решение
[https://github.com/Freeboard/freeboard/issues/111](url)
файл freeboard\plugins\freeboard\freeboard.widgets.js
замена строки 570
`height = $(element).height();`
на
`height = this.getHeight()*60;`

**Comment by sergejey** [comment]
Спасибо, я внёс изменение и загружу в ближайшее время в общую ветку.
