### ISSUE TITLE
Хардкод в адресе при запуске startWebSockets

### ISSUE THREAD

**Issue by palacex** [sergejey/majordomo#128]
Некорректный урл вебсокета т.к. порт и часть адреса прописаны не в настройках, а в коде.
Выявилось при попытке открыть список городов в приложении OpenWeather. Список так и не открылся.

MajorDoMo установлен из исходников gitgub'a.
Система: Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

**\templates\websockets.html** 
```php
 function startWebSockets() {
            var loc = window.location, new_uri;
            var serverUrl='';
            if (loc.protocol === "https:") {
                    serverUrl = "wss:";
            } else {
                    serverUrl = "ws:";
            }
            serverUrl += "//" + loc.host + ':<#WEBSOCKETS_PORT#>/majordomo';
...
```
**\load_settings.php**
```php
if (!defined('WEBSOCKETS_PORT'))
   Define('WEBSOCKETS_PORT', 8001);
```

**Как результат получаем это:**
![default](https://user-images.githubusercontent.com/4094859/30136254-c1f21d46-9366-11e7-86ec-0aff34ae5f8e.png)

**Вариант решения:**
Вынести в config.php порт web-сокета и его адрес.

**Comment by sergejey** [comment]
Не совсем понял суть проблемы.... Может быть дело в том, что был внешний доступ к системе и порт 8001 не проброшен наружу? Потому что судя по картинкам, URL для веб-сокета вполне корректный.

**Comment by palacex** [comment]
Ну почти... я полагаю проблема в том, что у меня MDM настроен так, чтобы работать через поддомен.
Например: 

- http://home.silvergate.ru (MDM)
- http://book.silvertgate.ru (Книжки)
и т.д.

А в скрипте добавляется "/majordomo" после порта.
Ресурса с таким адресом у меня нет, вот он и валится.

Т.е в моём случае работает вот так ws://home.silvergate.ru:8001

Собственно по этому и хотелось бы, чтобы вот эта часть адреса "/majordomo" была вынесена в настройки.

**Comment by sergejey** [comment]
Нет, не совсем так. При обращении к порту 8001 вообще не учитываются настройки веб-сервера, т.к. сервер веб-сокетов с ним не связан. Соответственно ресурс /majordomo так же к веб-серверу не относится и обрабатывается сервером веб-сокетов. Т.е. важно только чтобы домен home.silvergate.ru ссылался на нужный IP адрес и порт был открыт.

**Comment by palacex** [comment]
Ну тогда я не понимаю как так получается что если указан адрес  _ws://home.silvergate.ru:8001_, то запрос выполняется, а если адрес _ws://home.silvergate.ru:8001/majordomo_, то нет.

**Comment by dmitriytim** [comment]
Сергей являюсь фанатом вашего творчества, понимаю, что прошел похожие в этой ветке проблемы, с городом решилось так `/var/www/cached/openweather# wget https://raw.githubusercontent.com/crazycapivara/owmr/master/data-raw/city_list.txt` 
а вот с `:8001/majordomo` - нет
Читал, что пару лет назад можно было отключить WebSockets - сейчас в файле конфигурации этого нет, кроме того как быть в таком случае  `:8080:8001/majordomo` ? и даже при заходе с локальной сети браузеры как мозила так и хроме ругаются в консоли, что не могут получить доступы ws://123.123.123.123:8001/majordomo 
ЗЫ использую ubuntu - 18
