### ISSUE TITLE
Ошибка если в названии объектов есть дефис

### ISSUE THREAD

**Issue by andrei-trybukhouski** [sergejey/majordomo#158]
если в названии объектов есть дефис, то в админке простых устройств получаем 
light-corridor      Управляемое реле/Выключатель light-corridor, Коридор | %light-corridor.object_description% |

**Comment by Gelezako** [comment]
думаю тут всё ок, в программировании нельзя использовать дефис в имени объекта, тут аналогичный подход. Без дефиса можно жить. Для обозначения где находится устройство лучше используйте значение в выпадающем списке "Расположение". Так же есть специальный класс Rooms где можно организовать любую логику связанную с помещением. Новые помещения можно добавлять на странице Расположение, а так же можно добавлять новые объекты в классе Rooms.

**Comment by tribukhouski** [comment]
тут имя объекта - строка в базе, совсем не то, что идентификатор объекта в какомнить си. это не специальное ограничение, а баг.

**Comment by sergejey** [comment]
Это специальное ограничение, но баг есть и он в том, что система позволяет создавать сущности, не учитывая это ограничение.
