### ISSUE TITLE
Предложение по простым устройствам

### ISSUE THREAD

**Issue by tarasfrompir** [sergejey/majordomo#172]
Предлагаю дописать для датчика открытия/закрытия двери - метод MOTIONDETECTED
и включить его в метод SDevices_statusUpdated - поскольку открытие двери означает движение в комнате

**Comment by sergejey** [comment]
В датчике открытия/закрытия уже есть опция, что его сработка означает активность помещении. В таком случае он влияет на общий режим "никого нет дома" так же, как датчик движения и вызывает сработку метода onActivity для соответствующей комнаты. Если нужно, то какую-то логику можно уже туда дописывать.
