### ISSUE TITLE
Прошу прощения за навязчивость.  Простие устройства

### ISSUE THREAD

**Issue by tarasfrompir** [sergejey/majordomo#173]
Предлогаю ввести простое устройство - еллектродвигатель (вентилятор). Ато свет, кнoпки есть а електродвигателя как такого нет

**Comment by Gelezako** [comment]
А как вы представляете управление электродвигателем? Включить\выключить? Для этого есть реле.

**Comment by tarasfrompir** [comment]
Оно то есть, но, как в мажордомо отразить что у меня работает вытяжка - просто следуя Вашей логике , тогда и лампочки надо убрать и ргб и тд ведь все тоже включается через реле. (Любого типа толи выключатель, толи рубильник, толи симистор, толи оптопара)

**Comment by Gelezako** [comment]
Так и есть, и лампочки и вентилятор и электродвигатель включаются и выключаются путём переключения реле. Но каждый производитель пишет свой протокол через который можно удалённо вкл\выкл это самое реле. Из-за этого приходится постоянно писать новые модули, которые поддерживают этот протокол и новые способы доступа к этому самому реле для каждого устройства. 
Теперь касательно вашего вопроса. Если у вашего производителя есть своё АПИ или протокол доступа к функциям электродвигателя (вентилятора), то согласен, есть смысл его добавить как отдельное устройство. Но скорей всего его нет, поэтому и нет смысла добавлять такое устройство. И ваш выход - это добавить реле, назвать его электродвигатель и использовать в таком режиме.
