### ISSUE TITLE
Небезопасный файл php.php

### ISSUE THREAD

**Issue by fsa** [sergejey/majordomo#182]
В корневой папке проекта лежит небезопасный файл php.php. Он сообщает всю информацию о сервере любому, у кого есть доступ к сайту Majordomo, т.е. фактически систему выставлять в интернет опасно.

**Comment by dx168b** [comment]
Это было понятно сразу, как я начал знакомиться с системой. Мне пришлось открывать наружу MQTT брокер. Да, в MD есть профили пользователей, но система безопасности тут не развита от слова совсем. Нет даже банальной страницы авторизации при входе. Видимо, это связано с тем, что некоторые устройства держат связь с MD через http запросы. Это впринципе можно было бы решить генерацией токенов для устройств. Токен мог бы выступать как в качестве идентификатора устройства, так и в качестве элемента авторизации. Для запросов с токенами можно было бы урезать доступ так, чтобы по токену можно было только либо отдать технические данные, либо забрать. Лучше вообще сделать это дело настраиваемым. Что-то вроде прав и назначения токена. Один токен предназначен для устройства и ему доступно только два объекта. Другой токен предназначен для пользователя "Жена" и ему доступно только урезанное меню.

**Comment by warik-zp** [comment]
> Нет даже банальной страницы авторизации при входе.
Почему же нет? Basic auth в системе присутствует. Конфигурируется из config.php в корне системы.

**Comment by sergejey** [comment]
Систему выставлять в инет опасно. Это уже неоднократно обсуждалось. Авторизация есть и она настраиваемая, но работает для внешней сети, а домашняя сеть (настраивается через диапазон IP) для системы считается безопасной и там авторизации нет. Оптимально защищать всю сеть и организовывать доступ к системе через VPN.

**Comment by Gelezako** [comment]
Думаю что ничего страшного не произойдёт если мы удалим из проекта этот файл. Отправил пул реквест.
https://github.com/sergejey/majordomo/pull/194/commits/a0b5add6cc83344a124bc352a9c91b82e4d3d376

**Comment by tarasfrompir** [comment]
А закройте плиз это дело

**Comment by Gelezako** [comment]
закрыть может только или топик стартер @fsa или @sergejey
