### ISSUE TITLE
Ошибка с переменными в редакторе кода

### ISSUE THREAD

**Issue by Siorinex** [sergejey/majordomo#195]
Раньше в редактор вставлялось %ThisComputer.timeH% и оно выглядило в редакторе именно так, а в отображении уже как значение. Теперь после одного из последних апдейтов - в редактор попадает почему-то именно ЗНАЧЕНИЕ, а не код, в итоге изменить невозможно.
Пытался найти что так могло аукнуться, но не нашёл: вроде с этим всем никаких правок особо и не было...

**Comment by Siorinex** [comment]
В очередном исправлении исправилось...

**Comment by immortalserg** [comment]
исправилось только в меню, в сценах и в домашних страницах баг присутствует
