### ISSUE TITLE
Битая кодировка. 

### ISSUE THREAD

**Issue by palacex** [sergejey/majordomo#218]
Судя по истории так было изначально. т.е. создании файла.
Если это не используется, то может быть стоит удалить?
https://github.com/sergejey/majordomo/blob/86bbf6beb6267efefb10c929e5848d022e18423a/rc/sapi_cached.js#L316

**Comment by xor2016** [comment]
1. После // Finish ненужная функция вообще function Time2String(date)

**Comment by xor2016** [comment]
Кодировка OEM-866
