### ISSUE TITLE
При редактировании HTML элемента сцены пытается вписать NULL в свойство IMAGE

### ISSUE THREAD

**Issue by Siorinex** [sergejey/majordomo#260]
При редактировании HTML-элемента на сцене вывалило:
http://192.168.2.1/admin.php?pd=cGFuZWw6e2FjdGlvbj1zY2VuZXN9pz_&md=scenes&inst=adm&
1048: Column 'IMAGE' cannot be null
UPDATE `elm_states` SET `ID`='13', `ELEMENT_ID`='13', `TITLE`='default', `IMAGE`=NULL, `HTML`='', `IS_DYNAMIC`='0', `CURRENT_STATE`='1', `LINKED_OBJECT`='', `LINKED_PROPERTY`='', `CONDITION`='1', `CONDITION_VALUE`='', `CONDITION_ADVANCED`='', `SCRIPT_ID`='0', `SWITCH_SCENE`='0', `CURRENT_STATUS`='0', `ACTION_OBJECT`='', `ACTION_METHOD`='', `MENU_ITEM_ID`='0', `WINDOW_POSX`='0', `WINDOW_POSY`='0', `WINDOW_WIDTH`='0', `WINDOW_HEIGHT`='0', `HOMEPAGE_ID`='0', `EXT_URL`='', `PRIORITY`='0', `CODE`='', `OPEN_SCENE_ID`='0', `S3D_OBJECT`='', `S3D_CAMERA`='' WHERE ID = '13'

https://connect.smartliving.ru/diagnostic/10ff1snephv4okoc84wsswwkw  - диагностика

**Comment by Siorinex** [comment]
Похоже в https://github.com/sergejey/majordomo/blob/master/modules/scenes/scenes_edit.inc.php при заполнении полей в IMAGE попадает пустышка из переменной (352 строка) - подозреваю, что где-то система при чтении из поля пустой строки посчитала ее полностью нулевой. После чего  - формируется запрос "по полной" и в NOT NULL поле прилетает пустышка...

ИМХО - проще всего IMAGE перевести в поля, где NULL допустим, по аналогии с HTML и CODE полями...

**Comment by sergejey** [comment]
Должно быть исправлено.

**Comment by Siorinex** [comment]
Подтверждаю.
