### ISSUE TITLE
После обновления 30.08.2018 круговая загрузка свойств устройств в ПУ

### ISSUE THREAD

**Issue by tarasfrompir** [sergejey/majordomo#261]
Уважаемый Сергей после сегодняшнего обновления - снова загружает по кругу все устройства в странице ПУ.  
Эту проблему Вы уже решали путем ремонта загрузки Веб Сокетов...
Отремонтируйте плиз их

**Comment by sergejey** [comment]
Добрый день,

Может при установке обновления не запустились веб-сокеты? У себя проверил -- не наблюдаю подобное. Как оно в консоли браузера выглядит?

**Comment by tarasfrompir** [comment]
Прошу прощения - за ложный вызов.
Поскольку проверил дважды вебсокеты . 
Перезапускал Мажорика трижды.
Но пока не перезапустил компьютер - все нормализовалось
