### ISSUE TITLE
Не сохраняет перемещение элементов на сцене

### ISSUE THREAD

**Issue by dmitriytim** [sergejey/majordomo#265]
`/popup/scenes/1.html?draggable=1 - Uncaught TypeError: Converting circular structure to JSON; line: 842`
на сколько вижу js не может получить местоположение объектов и отправляет пустой запрос

**Comment by tarasfrompir** [comment]
А версия какая альфа или как? В альфе вроде исправлено...

**Comment by dmitriytim** [comment]
к сожалению не нашел где посмотреть устанавливал в ручную из скрипта установки для ubuntu `git clone https://github.com/sergejey/majordomo.git`  - обновляется с `https://github.com/sergejey/majordomo/archive/master.tar.gz`

**Comment by dmitriytim** [comment]
установил альфа, все работает
