### ISSUE TITLE
Отсутствует значение поля ид обьекта в таблице Методов

### ISSUE THREAD

**Issue by tarasfrompir** [sergejey/majordomo#286]
При создании любого простого устройства (из Вашего набора простых устройств ) - отсутствует OBJECT_ID в таблице methods хотя в таблице objects ИД обьекта существует..
Я так думаю что необходимо или удалить поле OBJECT_ID поскольку можна идентифицировать обьект по полю CLASS_ID или же исправить это "безобразие".....

**Comment by sergejey** [comment]
Методы относятся к классу и у них отсутствует OBJECT_ID до тех пор, пока кто-то не захочет добавить свою реализацию конкретного метода, который уже будет привязан к объекту.

**Comment by sergejey** [comment]
Кстати, нет необходимости дублировать issues отдельно в connect -- они там сами появляются.

**Comment by tarasfrompir** [comment]
По поводу коннекта извените не знал ...
Сразу там добавил а потом уже увидел....

По поводу привязки метода - я насколько понимаю если метод создан для отдельного обьекта то тогда должен бить ИД ?
Ну если все так то я закрываю этот вопрос
