### ISSUE TITLE
пустрые значения в таблице pvalues

### ISSUE THREAD

**Issue by tribukhouski** [sergejey/majordomo#292]
При создании объекта  в дереве   SDevices - SSensors - STempSensors и присвоении значения полям через админку в таблице pvalues создаются записи с пустым полем property_name. заполнено только поле property_id. Странно, но у созданных ранее сенсоров в этой таблице заполнены все поля правильно.
Пишу модуль, очень долго ловил, почему 6 устройст отрабатывает как надо, а седьмого не видит.

**Comment by sergejey** [comment]
Добрый день,
скажите пожалуйста, а как проиходит работа со значениями? Для всех функций должно быть достаточно заполнение property_id -- через него идёт связь с именем свойства, а property_name даже не очень помню для чего вводилось :)

**Comment by tribukhouski** [comment]
Сейчас я не использую ПУ и сказать уже ничего не могу.
