### ISSUE TITLE
Ошибка в выключателе  методе в меню управления

### ISSUE THREAD

**Issue by tribukhouski** [sergejey/majordomo#300]
При нажатии выключателя в меню в связанный метод не передаются парметр VALUE
в xray видится так 

`.switch {" VALUE" :" " ," OLD_VALUE" :" 0" ," ORIGINAL_OBJECT_TITLE" :" lamp1" }`

в отладчике в браузере запрос выглядит так
`http://192.168.1.208/ajax/commands.html?op=value_changed&item_id=118&new_value=`

**Comment by tribukhouski** [comment]
Это проявляется только если в поле данные что та записано. хотел использовать его для своих целей
Кстати зачем оно? и почему так влияет?

**Comment by tribukhouski** [comment]
Можно эту функциональность убрать без ущерба? хочу у выключателя это поле использовать для признака ридонли связанного свойства, чтобы сделать нормальную реакцию на обратную связь

**Comment by sergejey** [comment]
Убрать нет, нельзя. Режим read-only для связанного свойства мне помнится обсуждался, но я не нахожу такой задачи в разделе Идей, так что видимо оно потерялось. Это можно добавить как идею сюда: https://connect.smartliving.ru/tasks/1.html
