### ISSUE TITLE
Синтаксис MySQL 8

### ISSUE THREAD

**Issue by vy4eslavik** [sergejey/majordomo#419]
В системе не везде изолированы колонки с именем SYSTEM для запросов к базе. Не уверен по другим версиям, но MySQL 8 не воспринимает такой синтаксис. Большая просьба в следующее обновление включить кавычки для этих спецслов (`SYSTEM`).
В частности это наблюдается в файлах:
devices.class.php.
scenes.class.php
Возможно ещё где-то. Хорошо бы пройтись глобальным поиском.

У меня платформа работает на: Ubuntu 18; nginx; php 7.2; MySQL 8

**Comment by sergejey** [comment]
Спасибо, исправлено в альфа-ветке.
