### ISSUE TITLE
strlen() expects parameter 1 to be string, array given in /var/www/html/lib/caching.class.php on line 19

### ISSUE THREAD

**Issue by kirush0280** [sergejey/majordomo#438]
`Warning: strlen() expects parameter 1 to be string, array given in /var/www/html/lib/caching.class.php on line 19
`
However in PHP 5.3 and above, strlen() will return NULL for arrays. From the Manual: strlen() returns NULL when executed on arrays, and an E_WARNING level error is emitted. Prior [to 5.3.0] versions treated arrays as the string Array, thus returning a string length of 5 and emitting an E_NOTICE level error.

**Comment by sergejey** [comment]
For now caching for arrays is not supported so I have disabled data processing when value is an array. Thanks!
