### ISSUE TITLE
Несоответствие размеров полей SOURCE записываемым данным

### ISSUE THREAD

**Issue by tigerxp** [sergejey/majordomo#488]
У меня нет возможности отключить "strict mode" mysql, как рекомендуется в инструкциях по установке - нет доступа к конфигу mysql, так что по факту выгребаю ошибки. Основная проблема - в таблицах `phistory`, `phistory_queue` и `pvalues` (может, еще где-то - все не проверял) поле `SOURCE` объявлено как `varchar(20)`, тогда как в него пишутся гораздо более длинные строки, например, при добавлении данных от сценария espdata, установке/обновлении модулей, и много еще где, получаем:

`1406: Data too long for column 'SOURCE' at row 1`

Пока что у себя решил это увеличением длины поля в БД, но думаю, что здесь просто надо принять какое-то решение - либо обрезать строку перед вставкой в базу, либо изменить длину полей в этих таблицах.

**Comment by sergejey** [comment]
Спасибо, исправлено в альфе.
