### ISSUE TITLE
Ошибка в библиотеке phpmqtt

### ISSUE THREAD

**Issue by Kolunchik** [sergejey/majordomo#490]
Привет.
В библиотеке phpmqtt есть крайне неприятная ошибка, которая приводит к постоянным реконнектам к брокеру. Очень желательно бы её обновить.

Например, до https://raw.githubusercontent.com/SergeyBrook/phpMQTT/issue-42/phpMQTT.php

namespace нужно будет выкинуть :) Или подправить зависимый код.

Собственно, если этого не сделать, то каждые 15 секунд (интервал может зависеть от системы) происходит реконнект по таймауту и данные с брокера вычитываются заново, со всеми вытекающими обстоятельствами.

На графике загрузка CPU не слишком мощного компьютера. После 10 часов - с обновлённой библиотекой.

![image](https://user-images.githubusercontent.com/23293196/54739093-d96ec080-4bc7-11e9-887d-ed1b11b9ba85.png)

**Comment by sergejey** [comment]
Спасибо, обновил.
