### ISSUE TITLE
Расписание у простых устройств

### ISSUE THREAD

**Issue by Kolunchik** [sergejey/majordomo#492]
Привет.
Не работает расписание у простых устройств по причине 
`unset($rec['LINKED_OBJECT'])`
выше вызова
`callMethodSafe($rec['LINKED_OBJECT'] . '.' . $rec['LINKED_METHOD']);`
в файле devices.class.php. Т.е. вызывается не Relay08.turnOn, а просто .turnOn

Это так и задумано или ошибка?

**Comment by sergejey** [comment]
Привет.
Это ошибка, спасибо, будет исправлено.
