### ISSUE TITLE
Добавить ClearScheduledJob для исключения создания одноименных джобов

### ISSUE THREAD

**Issue by xor2016** [sergejey/majordomo#507]
https://github.com/sergejey/majordomo/blob/bac21724f0940e305b3e8da87858d4c6b4d75646/lib/common.class.php#L366

**Comment by xor2016** [comment]
Добавить первой строкой ClearScheduledJob для исключения создания одноименных джобов как для таймеров

**Comment by sergejey** [comment]
Готово.
