### ISSUE TITLE
Заявленное удаление по маске title% не будет работать

### ISSUE THREAD

**Issue by xor2016** [sergejey/majordomo#508]
https://github.com/sergejey/majordomo/blob/bac21724f0940e305b3e8da87858d4c6b4d75646/lib/common.class.php#L385

**Comment by xor2016** [comment]
Исправление:
`SQLExec("DELETE FROM jobs WHERE TITLE  like '" . DBSafe($title) . "'");`

**Comment by sergejey** [comment]
Спасибо, исправил.
