### ISSUE TITLE
Относительные пути

### ISSUE THREAD

**Issue by vy4eslavik** [sergejey/majordomo#520]
Хочу осветить одну проблемку. Разберу на примере файла `modules/market/market.class.php` строка 836:
Используется: `include_once(ROOT . 'modules/' . ` ...
То есть путь указан относительно корня приложения. Всё ок.
В том же файле строки 595, 774, 787, 800, 905:
Используется: `include_once(DIR_MODULES .  ` ...
А вот в примере конфига: `Define('DIR_MODULES', "./modules/");` соответственно подключение не отработает.

Я вижу два варианта решения:
1. Отказаться от `DIR_MODULES` и везде подключение заменить по типу:  `include_once(ROOT . 'modules/' . ` ...
2. Поправить конфиг, перенести в строку 55:
`
Define('DIR_TEMPLATES', ROOT."templates/");
Define('DIR_MODULES', ROOT."modules/");
`

Надеюсь понятно донёс )

**Comment by sergejey** [comment]
Спасибо. Исправлено в примере config-файла и будет исправлено в следующем релизе базового образа. При обновлении сейчас файл конфигурации не заменяется, поэтому в уже установленной системе это изменение можно только вручную произвести.
