### ISSUE TITLE
Не много ли подмен терминалов при проигрывании ?

### ISSUE THREAD

**Issue by tarasfrompir** [sergejey/majordomo#543]
вот отсюда 
https://github.com/sergejey/majordomo/blob/master/modules/app_player/app_player.class.php#L189
Может проще завернуть данный терминал если уж его не нашло или с ним какая проблемма

**Comment by sergejey** [comment]
Тут оно сделано на тот случай, если пользователь как-то криво сконфигурировал терминал или по какой-то причине вовсе терминалы не настроены. Мне кажется, что имеет смысл попытаться подобрать хоть что-то из имеющегося, нежели просто ничего не воспроизводить.
