### ISSUE TITLE
Лишний иф?

### ISSUE THREAD

**Issue by xor2016** [sergejey/majordomo#561]
https://github.com/sergejey/majordomo/blob/e9d137ace456521809740cb813f4583c552d8692/lib/common.class.php#L1390
Лишний иф?
```
    if ($player->json['success']) {
        return $player->json['message'];
    } else {
        return $player->json['message'];
    }
```

**Comment by tarasfrompir** [comment]
Ага по идее лишний...
Реквест подал закрывайте Иссу
