### ISSUE TITLE
Запросы с X-Ray

### ISSUE THREAD

**Issue by vy4eslavik** [sergejey/majordomo#571]
Шаги воспроизведения проблемы:
1. Заходим в "Панель управления"
2. Переходим в раздел "X-Ray".
   Наблюдаем как идут запросы вида: `admin.php?pd=eHJheTp7a`, для получения данных из логов.
3. Переходим в любой другой раздел. (например "Объекты")
   Наблюдаем как продолжают отправляться примерно те же запросы, но с "битыми" параметрами.

Причина:
Файл `xray.html`, функция `checkAllStates` после одного вызова бесконечно вызывает сама себя через таймаут. Но если мы находимся не в разделе "X-Ray", то эти данные нам не нужны, да и запрос формируется всё-равно с ошибкой.

Решение:
Решений множество, нужно выбрать оптимальное исходя из общей концепции системы. Для себя просто ставлю заглушку вида: `if(!$('#xrayContent').length) return;`.

**Comment by vy4eslavik** [comment]
Та же история с разделом "MQTT" кстати.
На мой взгляд такое обилие запросов могут негативно сказываться на скорости и в целом работоспособности админки.

**Comment by sergejey** [comment]
Здравствуйте. Спасибо, исправлено в недавних обновлениях альфы.
