### ISSUE TITLE
при редактирование элемента на сцене: опция "расширенная настройка" убивает привязку устройства или обьекта

### ISSUE THREAD

**Issue by deg026** [sergejey/majordomo#626]
при редактирование элемента на сцене
при включении опции "расширенная настройка"
исчезают поля привязки "устрояства" или "обьекта"
во первых непонятно вообще зачем?
как настройки позиционирования элемента влияют на привязку устройств/обьектов

так вот если был элемент с привязанным устройством:
1. заходим в редактирование
2. влючаем опцию "расширенная настройка" (EASY_CONFIG)
3. поля привязки исчезают, но они скрыты и есть в html форме
4. сохраняем с ВКЛЮЧЕННЫМ "расширенная настройка"
5. заного заходим в редактировани
6. теперь поля привязки/выбора устройства не подгрузились уже совсем в html форме (так прописано в шаблоне elements_edit.html
7. ничего не делая - жмем сохранить
8. вуаля, элемент поломан, связь с устройствои или обьектом потеряна, в БД в поле DEVICE_ID теперь стоит "0"

в чем суть скрытия дропдауна с устроствами при "расширенной настройке"?
возможно EASY_CONFIG раньше использовался немного в другом смысле и это просто глюк доставшийся из прошлого?
или тут есть какой-то тайный смысл который я не могу понять? :(

**Comment by sergejey** [comment]
Спасибо! Исправлено в альфа-ветке.
