### ISSUE TITLE
Исправление позиционирование елементов на сцене

### ISSUE THREAD

**Issue by NovakSergii** [sergejey/majordomo#641]
в [https://github.com/sergejey/majordomo/blob/master/templates/scenes/scenes.tpl#L667](https://github.com/sergejey/majordomo/blob/master/templates/scenes/scenes.tpl#L667)

`position:absolute;left:{$ELEMENT.LEFT}px;top:{$ELEMENT.TOP}px;`

заменить на

`{if $ELEMENT.POSITION_TYPE=="0"}position:absolute;left:{$ELEMENT.LEFT}px;top:{$ELEMENT.TOP}px;{/if}`

**Comment by sergejey** [comment]
Исправлено в альфе, спасибо.
