### ISSUE TITLE
Problem with scenes.

### ISSUE THREAD

**Issue by iveusss** [sergejey/majordomo#72]
After last updates, the scenes does not work properly. For example, when you add an lamp (light) on the scene and then press it, it won't light-up, but hardware is responding, then if you refresh the page, it shows light-on. Issue has weird bug, on the local ip can show normally and scenes has pages (1,2), on external ip - no pages. I also tried to set up new windows version with installer (and last repo updates), added my newer db, and had same problems. Then i installed version 0.9.0b from 29.01.2015, set up my db and all went ok.

**Comment by sergejey** [comment]
This bug is fixed. Please check the latest updates.
