### ISSUE TITLE
ALTER IGNORE TABLE doesn't work with new mysql version

### ISSUE THREAD

**Issue by dimitrystd** [sergejey/majordomo#76]
Got errors for during upgrade for statements like this
```
ALTER IGNORE TABLE public_calls ADD `TITLE` varchar(255) NOT NULL DEFAULT '';
```
From [mysql documentation](http://dev.mysql.com/doc/refman/5.7/en/alter-table.html)
```
As of MySQL 5.7.4, the IGNORE clause for ALTER TABLE is removed and its use produces an error. 
```
Please change approach of applying DB changes

**Comment by sergejey** [comment]
Fixed. "IGNORE" was not really necessary so just changed to "ALTER TABLE"
