### ISSUE TITLE
Problem with Ubuntu 16.04

### ISSUE THREAD

**Issue by vasvlad** [sergejey/majordomo#85]
After updating from Ubuntu 14 to Ubuntu16.04 I see error in log:
PHP Fatal error:  Cannot declare class error, because the name is already in use in /var/www/lib/errors.class.php on line 21

Seem like this problem  depend on php7
See here
http://php.net/manual/en/class.error.php

**Comment by vasvlad** [comment]
Temporary solution: switch to php 5.6
http://askubuntu.com/questions/761713/how-can-i-downgrade-from-php-7-to-php-5-6-on-ubuntu-16-04

**Comment by sergejey** [comment]
Please try it again as I have upgraded some code to be PHP7 friendly. Also, you should update addons installed as many of them have been updated as well.
