### ISSUE TITLE
modules/objects/objects.class.php - ошибка

### ISSUE THREAD

**Issue by tarasfrompir** [sergejey/majordomo#869]
https://github.com/sergejey/majordomo/blob/alpha/modules/objects/objects.class.php#L969
Както в классе нету такой переменной - не знаю для чего оно - но надо бы переосмыслить и переделать

**Comment by sergejey** [comment]
Берём поиск и "на раз" находим эту переменную :) Этот код работает в точности как задумано для синхронизации с коннектом, без указанного условия оно работать не будет.

**Comment by tarasfrompir** [comment]
Да ну так то вроде да - но функция  то не вызывается например при вызове сетпроперти... Или я не прав....
