### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by TheDramaMan** [sergejey/majordomo#92]
It seems, you're using php. It's very bad, I propose Go or Node.JS for this project, it much better than that horrible language.

**Comment by GermanBluefox** [comment]
I think it is kind of trolling?
Every language is good enough if solution works. :) If people understand better Php, then Go, nothing will help them in go project.
There are no noticeable home automation projects on Go (if you know one,  let me know ), but I can tell a couple in node.js: ioBroker, pimatic, the thing system.

**Comment by sergejey** [comment]
Well... what can I say here? :) Who am I to stop you from starting another home automation project with Go or Node.JS :)
